name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: linux-amd64-${{ runner.os }}-go-${{ hashFiles('go.sum') }}
      - name: Download Tools
        run: make download-tools
      - name: Build linux-amd64
        run: make build-linux-amd64
      - name: Upload linux-amd64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: gotify-github-plugin-linux-amd64
          path: build/gotify-github-plugin-linux-amd64*.so

  build-linux-arm-7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: linux-arm-7-${{ runner.os }}-go-${{ hashFiles('go.sum') }}
      - name: Download Tools
        run: make download-tools
      - name: Build linux-arm-7
        run: make build-linux-arm-7
      - name: Upload linux-arm-7 artifact
        uses: actions/upload-artifact@v4
        with:
          name: gotify-github-plugin-linux-arm-7
          path: build/gotify-github-plugin-linux-arm-7*.so

  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: linux-arm64-${{ runner.os }}-go-${{ hashFiles('go.sum') }}
      - name: Download Tools
        run: make download-tools
      - name: Build linux-arm64
        run: make build-linux-arm64
      - name: Upload linux-arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: gotify-github-plugin-linux-arm64
          path: build/gotify-github-plugin-linux-arm64*.so